apiVersion: v1
kind: Service
metadata:
  name: dev-logstash
  namespace: kube-system
  labels:
    component: dev-logstash
spec:
  selector:
    component: dev-logstash
  ports:
  - name: dev-logstash
    port: 5043
    protocol: TCP

