apiVersion: v1
kind: Service
metadata:
  name: l-logstash
  namespace: kube-system
  labels:
    component: l-logstash
spec:
  selector:
    component: l-logstash
  ports:
  - name: l-logstash
    port: 5043
    protocol: TCP

