---
- name: create es images directory
  file: path=/tmp/images state=directory

- name: copy es images
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - {src: 'es.tar', dest: '/tmp/images/es.tar'  }

- name: docker import es images
  shell: docker load -i {{ item }}
  with_items:
    - /tmp/images/es.tar

- name: create kibana conf directory
  file: path=/tmp/es state=directory

- name: copy kibana conf
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - {src: 'es-master-svc.yml', dest: '/tmp/es/es-master-svc.yaml'}
    - {src: 'es-data-pdb.yml', dest: '/tmp/es/es-data-pdb.yml'}
    - {src: 'es-client-svc.yml', dest: '/tmp/es/es-client-svc.yml'}

- name: create elasticsearch pod and svc
  shell: kubectl create -f /tmp/es
  
- name: delete /tmp/es
  shell: rm -rf /tmp/es 
