###################### Filebeat Configuration Example #########################

# This file is an example configuration file highlighting only the most common
# options. The filebeat.full.yml file from the same directory contains all the
# supported options with more comments. You can use it as a reference.
#
# You can find the full configuration reference here:
# https://www.elastic.co/guide/en/beats/filebeat/index.html

#=========================== Filebeat prospectors =============================

filebeat.prospectors:

# Each - is a prospector. Most options can be set at the prospector level, so
# you can use different prospectors for various configurations.
- input_type: log
  paths:
    - /var/log/nova/nova-compute.log
  document_type: nova-compute
  fields:
    IP: 10.2.29.10
  multiline.pattern: ^\d{4}-\d{2}-\d{2}\s
  multiline.negate: true
  multiline.match: after
  tail_files: true
- input_type: log
  paths:
    - /var/log/nova/nova-manage.log
  document_type: nova-manage
  fields:
    IP: 10.2.29.10
  multiline.pattern: ^\d{4}-\d{2}-\d{2}\s
  multiline.negate: true
  multiline.match: after
  tail_files: true
- input_type: log
  paths:
    - /var/log/ceph/ceph-osd.*.log
  document_type: ceph-osd
  fields:
    IP: 10.2.29.10
  multiline.pattern: ^\d{4}-\d{2}-\d{2}\s
  multiline.negate: true
  multiline.match: after
  tail_files: true
- input_type: log
  paths:
    - /var/log/auth.log
  document_type: ssh
  fields:
     IP: 10.2.29.10
  multiline.pattern: ^[A-Z][a-z][a-z]\s
  multiline.negate: true
  multiline.match: after
  tail_files: true
- input_type: log
  paths:
    - /var/log/syslog
  document_type: syslog
  fields:
     IP: 10.2.29.10
  multiline.pattern: ^[A-Z][a-z][a-z]\s
  multiline.negate: true
  multiline.match: after
  tail_files: true
# Below are the prospector specific configurations.


  # Paths that should be crawled and fetched. Glob based paths.
    #- c:\programdata\elasticsearch\logs\*

  # Exclude lines. A list of regular expressions to match. It drops the lines that are
  # matching any regular expression from the list.
  #exclude_lines: ["^DBG"]

  # Include lines. A list of regular expressions to match. It exports the lines that are
  # matching any regular expression from the list.
  #include_lines: ["^ERR", "^WARN"]

  # Exclude files. A list of regular expressions to match. Filebeat drops the files that
  # are matching any regular expression from the list. By default, no files are dropped.
  #exclude_files: [".gz$"]

  # Optional additional fields. These field can be freely picked
  # to add additional information to the crawled log files for filtering
  #fields:
  #  level: debug
  #  review: 1

  ### Multiline options

  # Mutiline can be used for log messages spanning multiple lines. This is common
  # for Java Stack Traces or C-Line Continuation

  # The regexp Pattern that has to be matched. The example pattern matches all lines starting with [
  #multiline.pattern: ^\[

  # Defines if the pattern set under pattern should be negated or not. Default is false.
  #multiline.negate: false

  # Match can be set to "after" or "before". It is used to define if lines should be append to a pattern
  # that was (not) matched before or after or as long as a pattern is not matched based on negate.
  # Note: After is the equivalent to previous and before is the equivalent to to next in Logstash
  #multiline.match: after
 # tail_files: true


#================================ General =====================================

# The name of the shipper that publishes the network data. It can be used to group
# all the transactions sent by a single shipper in the web interface.
#name:

# The tags of the shipper are included in their own field with each
# transaction published.
#tags: ["service-X", "web-tier"]

# Optional fields that you can specify to add additional information to the
# output.
#fields:
#  env: staging

#================================ Outputs =====================================

# Configure what outputs to use when sending the data collected by the beat.
# Multiple outputs may be used.

#-------------------------- Elasticsearch output ------------------------------
#output.elasticsearch:
  # Array of hosts to connect to.
#  hosts: ["localhost:9200"]

  # Optional protocol and basic auth credentials.
  #protocol: "https"
  #username: "elastic"
  #password: "changeme"

#----------------------------- Logstash output --------------------------------
#
  # The Logstash hosts
#: ["10.2.5.2:5044"]

  # Optional SSL. By default is off.
  # List of root certificates for HTTPS server verifications
  #ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]

  # Certificate for SSL client authentication
  #ssl.certificate: "/etc/pki/client/cert.pem"

  # Client Certificate Key
  #ssl.key: "/etc/pki/client/cert.key"

#================================ Logging =====================================

# Sets log level. The default log level is info.
# Available log levels are: critical, error, warning, info, debug
#logging.level: debug

# At debug level, you can selectively enable logging only for some components.
# To enable all selectors use ["*"]. Examples of other selectors are "beat",
# "publish", "service".
#logging.selectors: ["*"]



#------------------------------- Kafka output ----------------------------------
output.kafka:
  # Boolean flag to enable or disable the output module.
  enabled: true

  # The list of Kafka broker addresses from where to fetch the cluster metadata.
  # The cluster metadata contain the actual Kafka brokers events are published
  # to.
  hosts: ["10.2.5.2:9092","10.2.5.3:9092","10.2.5.4:9092"]

  # The Kafka topic used for produced events. The setting can be a format string
  # using any event field. To set the topic from document type use `%{[type]}`.
  topic: openstack3
